# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(483, 600)
        self.pushButton = QtWidgets.QPushButton(main)
        self.pushButton.setGeometry(QtCore.QRect(250, 210, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(main)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 210, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(main)
        self.lineEdit.setGeometry(QtCore.QRect(210, 110, 131, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(main)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 150, 131, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label = QtWidgets.QLabel(main)
        self.label.setGeometry(QtCore.QRect(130, 110, 61, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(main)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 47, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(main)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 47, 13))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "main"))
        self.pushButton.setText(_translate("main", "Вход"))
        self.pushButton_2.setText(_translate("main", "Выход"))
        self.label.setText(_translate("main", "Логин"))
        self.label_2.setText(_translate("main", "Пароль"))
        self.label_3.setText(_translate("main", "Авторизация"))
